module.exports = {
  "basics" : require('./basics'),
  "directional" : require('./directional'),
  "create-ten-elements" : require('./create-ten-elements'),
  "create-ten-elements-returns" : require('./create-ten-elements-returns'),
  "accidental-globals" : require('./accidental-globals'),
  "function-capture" : require('./function-capture'),
  "bind-event" : require('./bind-event'),
  "handler-leak" : require('./handler-leak'),
  "handler-leak-fix" : require('./handler-leak-fix'),
  "retaining-paths" : require('./retaining-paths'),
  "object-vs-map" : require('./object-vs-map'),
  "map-cache" : require('./map-cache'),
  "weakmap-cache" : require('./weakmap-cache'),
}
